// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteDevCartsys.Data;

#nullable disable

namespace TesteDevCartsys.Migrations
{
    [DbContext(typeof(TesteDevCartsysContext))]
    [Migration("20240805154745_Relação Contato e TipoContato")]
    partial class RelaçãoContatoeTipoContato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteDevCartsys.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("TipoContatoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoContatoId")
                        .IsUnique();

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("TesteDevCartsys.Models.TipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposContato");
                });

            modelBuilder.Entity("TesteDevCartsys.Models.Contato", b =>
                {
                    b.HasOne("TesteDevCartsys.Models.TipoContato", "TipoContato")
                        .WithOne("Contato")
                        .HasForeignKey("TesteDevCartsys.Models.Contato", "TipoContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoContato");
                });

            modelBuilder.Entity("TesteDevCartsys.Models.TipoContato", b =>
                {
                    b.Navigation("Contato")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
